### ISSUE TITLE
[shape] animation stops when I change tab, minimize window screen, etc

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/UI-Shape#1]
Hello there,

I'm having a very serious problem with Semantic UI - shape.
Whenever I change tab, minimize window screen, ...
If the animation is not displayed and is run on the background, the entire 'shape' animation stops displaying.

I've done my best correcting my code, and the jQuery 'shape' functions are running as usual.
The problem seems to be located either inside the "semantic.min.css" or "semantic.min.js"
Could anyone help me here ?

P.S: here's a link to test what I'm talking about.
https://jsfiddle.net/qjcv2Lu3/30/
(check out the console log... : 'toto' is displayed as proof that my code is working and is executing the 'shape' function as well).

**Comment by ghost** [comment]
It's been three days already... Is anyone active here on Semantic-Org ?

**Comment by jlukic** [comment]
Hi, the proper board is:
https://github.com/Semantic-Org/Semantic-UI/issues

For debugging your project code I'd recommend either [the ProjectTalk message board](http://www.projecttalk.io/boards/Semantic-Org%2FSemantic-UI), [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui) or [Gitter](https://gitter.im/Semantic-Org/Semantic-UI).

See our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for an explanation of how to properly submit bug reports.
